language: node_js
node_js:
- "node"
cache: npm
script: 
- npm run deploy
- npm run test
after_script: npm run alias
env:
  global:
    secure: kzhomdS1rwJMAZtLGmw9RmfNltXQwOLay4X89ydH1x9wmpZG5Y3A0h7d1+aTqMkz2NGUd97SXlJpngR4LYCmi0isw3flelNP0tacJfPiCl0GI6voUI4i6WkStgDwP3kfnk/zOW4faCOV35XRLjT3G/McSWQ4/M+Bno+Jdn+LeZGKMIwIjfG/W8r5vZCSCyHrBtMAVIRVlb7kQH/dAJiFVnE72oUCidfr5ExjEAFuGfRGvgOvTsKFNUeNULKyoaIM0KKDIx++WMVbY3JR0gRrdWdttYg3xat7+xcBJjc8UQymCQoglipPVENGfzw9+yipMFK3CoaXu0rYgxlDrqQ3PZoR+ki5py/jSYnIU7b4+lAEQYLojszvbenAvq9NdbxcchxBzrNbEnvjsHe8wqlfU3n5F1IlwXtBrwt21zrf/LyoZu7AKArWWg4kpaSKYJPQrT77Sc8/TLJmygSUDCBQ3se2hHUiyhiPnMOVsOHJ8IToQ+/giN4BylXosP2OzHBWkhRkvfmRdvNkZjMz5L/STKsB8ucFRbGeOhwbEL02cYCNAhMMpqZheMEd2eQOnlOlp332QjCDZvAaCDkt7WN9vnIyygDn5kCQZcdUrpWfQlj8/s1X4jWBF142T7HOu0ZCtQJexdCQBcUnGGwWbQzQ0QnIEs/S0q3cGHKdWneQGlU=
